/// Represents a lawyer's professional profile in the legal services platform.
///
/// This entity stores comprehensive professional information about a lawyer,
/// including their credentials, experience, areas of practice, and professional metrics.
/// Each profile is uniquely associated with a single user account through a one-to-one
/// relationship.
/// ### Key Features:
///
///     - Bar council registration details and verification status
///     - Professional experience and specializations
///     - Court types and practice areas
///     - Professional metrics including cases solved and average rating
///     - Service pricing information
///
///
/// This entity is mapped to the `lawyer_profiles` table in the database,
/// with related collections stored in separate join tables.
///
/// @see User
/// @see VerificationStatus
///
/// @author shivaverabandi - BruteForce.com
/// @version 1.0
/// @since 2025-10-22
package com.bruteforce.userasaservice.model;

import jakarta.persistence.*;
import org.hibernate.annotations.UuidGenerator;

import java.math.BigDecimal;
import java.util.Set;
import java.util.UUID;

/// Entity representing a lawyer profile.
///
/// Mapped to the database table `lawyer_profiles`. Each profile is linked one-to-one
/// with a `User` entity via `userId`. Contains professional metadata such as
/// bar council details, specializations, court types, verification status
/// metrics like ratings and apprenticeships.
@Entity
@Table(
        name = "lawyer_profiles",
        // index on bar_council_id and bar_council_state for faster lookup
        indexes = {
                @Index(name = "idx_bar_council_composite", columnList = "bar_council_id, bar_council_state")
        },
        // unique constraint on bar_council_id and bar_council_state
        uniqueConstraints = @UniqueConstraint(
                name = "uk_lawyer_bar_council",
                columnNames = {"bar_council_id", "bar_council_state"}
        )
)
public class LawyerProfile {

    /// Primary key for the lawyer profile. UUID generated by Hibernate.
    /// Column: `user_id` (UUID), non-updatable and non-nullable.
    @Id
    @GeneratedValue
    @UuidGenerator
    @Column(name = "lawyer_id", updatable = false, nullable = false, columnDefinition = "UUID")
    private UUID lawyerId;

    /// Associated user account for this lawyer profile.
    /// One-to-one relationship joined on `user_id`. Uses lazy loading.
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", referencedColumnName = "user_id",
            nullable = false, updatable = false, columnDefinition = "UUID",
            unique = true,foreignKey = @ForeignKey(name = "FK_LAWYER_USER"))
    private User user;

    /// Official bar council ID for the lawyer.
    /// Column: `bar_council_id` (VARCHAR(255)), unique and required.
    @Column(name = "bar_council_id", nullable = false)
    private String barCouncilId;

    /// State or region of the bar council where the lawyer is registered.
    /// Column: `bar_council_state` (VARCHAR(255)), required.
    @Column(name = "bar_council_state",nullable = false)
    private String barCouncilState;

    /// Number of years of professional legal experience.
    /// Column: `years_of_experience`, required.
    @Column(name = "years_of_experience", nullable = false)
    private Integer yearsOfExperience;

    /// Set of the lawyer's specializations (e.g., corporate, family, criminal).
    /// Stored in a separate collection table `lawyer_specializations` joined by `user_id`.
    @ElementCollection
    @CollectionTable(
            name = "lawyer_specializations",
            joinColumns = @JoinColumn(name = "user_id")
    )
    @Column(name = "specialization")
    private Set<String> specializations;

    /// Types of courts the lawyer practices in (stored as text).
    /// Stored in `lawyer_court_types` collection table joined by `user_id`.
    @ElementCollection
    @CollectionTable(
            name = "lawyer_court_types",
            joinColumns = @JoinColumn(name = "user_id")
    )
    @Column(name = "court_type", columnDefinition = "text")
    private Set<String> courtTypes;

    /// URL to the verification document (if provided).
    /// Column: `verification_document_url` (VARCHAR(500)), optional.
    @Column(name = "verification_document_url", length = 500)
    private String verificationDocumentUrl;

    /// Current verification status for the lawyer profile.
    /// Enum persisted as String in `verification_status` column, defaults to NONE.
    @Enumerated(EnumType.STRING)
    @Column(name = "verification_status", length = 20, nullable = false)
    private VerificationStatus verificationStatus = VerificationStatus.NOT_VERIFIED;

    /// Number of cases the lawyer has solved.
    /// Column: `cases_solved`, defaults to 0.
    @Column(name = "cases_solved", nullable = false)
    private Integer casesSolved = 0;

    /// Average rating of the lawyer (scale 0.00 - 5.00 typically).
    /// Column: `average_rating` with precision and scale defined, defaults to 0.00.
    @Column(name = "average_rating", precision = 3, scale = 2, nullable = false)
    private BigDecimal averageRating = BigDecimal.ZERO;

    /// Hourly rate charged by the lawyer.
    /// Column: `hourly_rate`, decimal with precision and scale.
    @Column(name = "price", precision = 10, scale = 2)
    private BigDecimal hourlyRate;


    // ==================== Getters and Setters ====================


    public UUID getLawyerId() {
        return lawyerId;
    }

    public void setLawyerId(UUID lawyerId) {
        this.lawyerId = lawyerId;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getBarCouncilId() {
        return barCouncilId;
    }

    public void setBarCouncilId(String barCouncilId) {
        this.barCouncilId = barCouncilId;
    }

    public String getBarCouncilState() {
        return barCouncilState;
    }

    public void setBarCouncilState(String barCouncilState) {
        this.barCouncilState = barCouncilState;
    }

    public Integer getYearsOfExperience() {
        return yearsOfExperience;
    }

    public void setYearsOfExperience(Integer yearsOfExperience) {
        this.yearsOfExperience = yearsOfExperience;
    }

    public Set<String> getSpecializations() {
        return specializations;
    }

    public void setSpecializations(Set<String> specializations) {
        this.specializations = specializations;
    }

    public Set<String> getCourtTypes() {
        return courtTypes;
    }

    public void setCourtTypes(Set<String> courtTypes) {
        this.courtTypes = courtTypes;
    }

    public String getVerificationDocumentUrl() {
        return verificationDocumentUrl;
    }

    public void setVerificationDocumentUrl(String verificationDocumentUrl) {
        this.verificationDocumentUrl = verificationDocumentUrl;
    }

    public VerificationStatus getVerificationStatus() {
        return verificationStatus;
    }

    public void setVerificationStatus(VerificationStatus verificationStatus) {
        this.verificationStatus = verificationStatus;
    }

    public Integer getCasesSolved() {
        return casesSolved;
    }

    public void setCasesSolved(Integer casesSolved) {
        this.casesSolved = casesSolved;
    }

    public BigDecimal getAverageRating() {
        return averageRating;
    }

    public void setAverageRating(BigDecimal averageRating) {
        this.averageRating = averageRating;
    }

    public BigDecimal getHourlyRate() {
        return hourlyRate;
    }

    public void setHourlyRate(BigDecimal hourlyRate) {
        this.hourlyRate = hourlyRate;
    }
}
