
/// Represents a lawyer's professional profile in the legal services platform.
///
/// This entity stores comprehensive professional information about a lawyer,
/// including their credentials, experience, areas of practice and professional metrics.
/// Each profile is uniquely associated with a single user account through a one-to-one
/// relationship.
///
/// Key features include:
///
///     - Bar council registration details and verification status
///     - Professional experience and specializations
///     - Court types and practice areas
///     - Professional metrics including cases solved and average rating
///     - Service pricing information
///
///
///
/// This entity is mapped to the `lawyer_profiles` table in the database,
/// with related collections stored in separate join tables.
///
/// @see User
/// @see VerificationStatus
package com.bruteforce.userasaservice.model;

import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.Id;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Column;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.OneToOne;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ElementCollection;
import jakarta.persistence.CollectionTable;
import jakarta.persistence.FetchType;
import jakarta.persistence.ForeignKey;
import org.hibernate.annotations.UuidGenerator;
import java.util.Set;
import java.util.UUID;

/**
 * Entity representing a lawyer profile.
 *
 * <p>Mapped to the database table `lawyer_profiles`. Each profile is linked one-to-one
 * with a `User` entity via `userId`. Contains professional metadata such as
 * bar council details, specializations, court types, verification status and
 * metrics like ratings and apprenticeships.</p>
 */
@Entity
@Table(name = "lawyer_profiles")
public class LawyerProfile {

    /**
     * Primary key for the lawyer profile. UUID generated by Hibernate.
     *
     * Column: `user_id` (UUID), non-updatable and non-nullable.
     */
    @Id
    @GeneratedValue
    @UuidGenerator
    @Column(name = "lawyer_id", updatable = false, nullable = false, columnDefinition = "UUID")
    private UUID lawyerId;

    /**
     * Associated user account for this lawyer profile.
     *
     * One-to-one relationship joined on `user_id`. Uses lazy loading.
     */

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", referencedColumnName = "user_id",
            nullable = false, updatable = false, columnDefinition = "UUID",
            unique = true,foreignKey = @ForeignKey(name = "FK_LAWYER_USER"))
    private User user;

    /**
     * Official bar council ID for the lawyer.
     *
     * Column: `bar_council_id` (VARCHAR(100)), unique and required.
     */
    @Column(name = "bar_council_id", nullable = false, unique = true, length = 100)
    private String barCouncilId;

    /**
     * State or region of the bar council where the lawyer is registered.
     *
     * Column: `bar_council_state` (VARCHAR(100)), optional.
     */
    @Column(name = "bar_council_state", length = 100)
    private String barCouncilState;

    /**
     * Number of years of professional legal experience.
     *
     * Column: `years_of_experience`, required.
     */
    @Column(name = "years_of_experience", nullable = false)
    private Integer yearsOfExperience;

    /**
     * Set of the lawyer's specializations (e.g., corporate, family, criminal).
     *
     * Stored in a separate collection table `lawyer_specializations` joined by `user_id`.
     */
    @ElementCollection
    @CollectionTable(
            name = "lawyer_specializations",
            joinColumns = @JoinColumn(name = "user_id")
    )
    @Column(name = "specialization")
    private Set<String> specializations;

    /**
     * Types of courts the lawyer practices in (stored as text).
     *
     * Stored in `lawyer_court_types` collection table joined by `user_id`.
     */
    @ElementCollection
    @CollectionTable(
            name = "lawyer_court_types",
            joinColumns = @JoinColumn(name = "user_id")
    )
    @Column(name = "court_type", columnDefinition = "text")
    private Set<String> courtTypes;

    /**
     * URL to the verification document (if provided).
     *
     * Column: `verification_document_url` (VARCHAR(500)), optional.
     */
    @Column(name = "verification_document_url", length = 500)
    private String verificationDocumentUrl;

    /**
     * Current verification status for the lawyer profile.
     *
     * Enum persisted as String in `verification_status` column, defaults to NONE.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "verification_status", length = 20, nullable = false)
    private VerificationStatus verificationStatus = VerificationStatus.NOT_VERIFIED;

    /**
     * Number of cases the lawyer has solved.
     *
     * Column: `cases_solved`, defaults to 0.
     */
    @Column(name = "cases_solved", nullable = false)
    private Integer casesSolved = 0;

    /**
     * Average rating of the lawyer (scale 0.00 - 5.00 typically).
     *
     * Column: `average_rating` with precision and scale defined, defaults to 0.00.
     */
    @Column(name = "average_rating", precision = 3, scale = 2, nullable = false)
    private Double averageRating = 0.00;

    /**
     * Hourly rate charged by the lawyer.
     *
     * Column: `hourly_rate`, decimal with precision and scale.
     */
    @Column(name = "hourly_rate", precision = 10, scale = 2)
    private Double hourlyRate;

}
