/// Represents a lawyer's professional profile in the legal services platform.
///
/// This entity stores comprehensive professional information about a lawyer,
/// including their credentials, experience, areas of practice, and professional metrics.
/// Each profile is uniquely associated with a single user account through a one-to-one
/// relationship.
/// ### Key Features:
///
///     - Bar council registration details and verification status
///     - Professional experience and specializations
///     - Court types and practice areas
///     - Professional metrics including cases solved and average rating
///     - Service pricing information
///
///
/// This entity is mapped to the `lawyer_profiles` table in the database,
/// with related collections stored in separate join tables.
///
/// @see User
/// @see VerificationStatus
///
/// @author shivaverabandi - BruteForce.com
/// @version 1.0
/// @since 2025-10-22
package com.bruteforce.lawforall.model;

import jakarta.persistence.*;
import org.hibernate.annotations.UuidGenerator;

import java.math.BigDecimal;
import java.util.Set;
import java.util.UUID;

/// Entity representing a lawyer profile.
///
/// Mapped to the database table `lawyer_profiles`. Each profile is linked one-to-one
/// with a `User` entity via `userId`. Contains professional metadata such as
/// bar council details, specializations, court types, verification status
/// metrics like ratings and apprenticeships.
@Entity
@Table(name = "lawyer_profiles")
public class LawyerProfile {

    /// Primary key for the lawyer profile. UUID generated by Hibernate.
    /// Column: `user_id` (UUID), non-updatable and non-nullable.
    @Id
    @GeneratedValue
    @UuidGenerator
    @Column(name = "lawyer_id", updatable = false, nullable = false, columnDefinition = "UUID")
    private UUID lawyerId;

    /// Associated user account for this lawyer profile.
    /// One-to-one relationship joined on `user_id`. Uses lazy loading.
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", referencedColumnName = "user_id",
            nullable = false, updatable = false, columnDefinition = "UUID",
            unique = true,foreignKey = @ForeignKey(name = "FK_LAWYER_USER"))
    private User user;

    /// Number of years of professional legal experience.
    /// Column: `years_of_experience`, required.
    @Column(name = "years_of_experience", nullable = false)
    private Integer yearsOfExperience;

    /// Set of the lawyer's specializations (e.g., corporate, family, criminal).
    /// Stored in a separate collection table `lawyer_specializations` joined by `user_id`.
    @ElementCollection
    @CollectionTable(
            name = "lawyer_specializations",
            joinColumns = @JoinColumn(name = "user_id")
    )
    @Column(name = "specialization")
    private Set<String> specializations;

    /// Types of courts the lawyer practices in (stored as text).
    /// Stored in `lawyer_court_types` collection table joined by `user_id`.
    @ElementCollection
    @CollectionTable(
            name = "lawyer_court_types",
            joinColumns = @JoinColumn(name = "user_id")
    )
    @Column(name = "court_type", columnDefinition = "text")
    private Set<String> courtTypes;


    /// Number of cases the lawyer has solved.
    /// Column: `cases_solved`, defaults to 0.
    @Column(name = "cases_solved", nullable = false)
    private Integer casesSolved = 0;



    public LawyerProfile() {

    }

    public LawyerProfile(UUID lawyerId, User user, Integer yearsOfExperience,
                         Set<String> specializations, Set<String> courtTypes,
                         Integer casesSolved) {
        this.lawyerId = lawyerId;
        this.user = user;
        this.yearsOfExperience = yearsOfExperience;
        this.specializations = specializations;
        this.courtTypes = courtTypes;
        this.casesSolved = casesSolved;
    }

   // Getters & Setters

    public UUID getLawyerId() {
        return lawyerId;
    }

    public void setLawyerId(UUID lawyerId) {
        this.lawyerId = lawyerId;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Integer getYearsOfExperience() {
        return yearsOfExperience;
    }

    public void setYearsOfExperience(Integer yearsOfExperience) {
        this.yearsOfExperience = yearsOfExperience;
    }

    public Set<String> getSpecializations() {
        return specializations;
    }

    public void setSpecializations(Set<String> specializations) {
        this.specializations = specializations;
    }

    public Set<String> getCourtTypes() {
        return courtTypes;
    }

    public void setCourtTypes(Set<String> courtTypes) {
        this.courtTypes = courtTypes;
    }

    public Integer getCasesSolved() {
        return casesSolved;
    }

    public void setCasesSolved(Integer casesSolved) {
        this.casesSolved = casesSolved;
    }

    // Builder Pattern Implementation
    public static class LawyerProfileBuilder {
        private UUID lawyerId;
        private User user;
        private Integer yearsOfExperience;
        private Set<String> specializations;
        private Set<String> courtTypes;
        private Integer casesSolved;

        public LawyerProfileBuilder() {
        }
        public LawyerProfileBuilder lawyerId(UUID lawyerId) {
            this.lawyerId = lawyerId;
            return this;
        }
        public LawyerProfileBuilder user(User user) {
            this.user = user;
            return this;
        }
        public LawyerProfileBuilder yearsOfExperience(Integer yearsOfExperience) {
            this.yearsOfExperience = yearsOfExperience;
            return this;
        }
        public LawyerProfileBuilder specializations(Set<String> specializations) {
            this.specializations = specializations;
            return this;
        }
        public LawyerProfileBuilder courtTypes(Set<String> courtTypes) {
            this.courtTypes = courtTypes;
            return this;
        }
        public LawyerProfileBuilder casesSolved(Integer casesSolved) {
            this.casesSolved = casesSolved;
            return this;
        }
        public LawyerProfile build() {
            return new LawyerProfile(lawyerId, user, yearsOfExperience, specializations, courtTypes, casesSolved);
        }
    }
}


