/// Represents a user in the system with authentication and profile information.
///
/// This entity is the central identity model that supports multiple authentication methods,
/// including email/password and OAuth providers. It serves as the base for role-based access control
/// with support for PUBLIC, ADMIN, and LAWYER roles.
/// ### Key Features:
///
///     - Supports both traditional (email/password) and OAuth authentication
///     - Role-based access control with default to the PUBLIC role
///     - Email and phone verification status tracking
///     - Account activation/deactivation support
///     - Automatic audit fields (createdAt, updatedAt)
///     - Optional lawyer profile association for users with LAWYER role
///
/// ### Database Constraints:
///
///     - Unique constraint on (oauth_provider, oauth_id) for OAuth authentication
///     - Unique constraint on email, username, and phoneNumber
///     - Indexes on frequently queried fields for performance
///
///
/// @author shivaverabandi - BruteForce.com
/// @version 1.0
/// @since 2025-10-22
/// @see Role
/// @see LawyerProfile

package com.bruteforce.lawforall.model;
import jakarta.persistence.*;

import java.time.LocalDateTime;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.annotations.UuidGenerator;

import java.util.UUID;

@Entity
@Table(
        name = "users",
        indexes = {
                @Index(name = "idx_user_username", columnList = "username", unique = true),
                @Index(name = "idx_user_phone", columnList = "phoneNumber", unique = true)
        }
)
public class User {
    /// The user's unique identifier. Automatically generated as a UUID.
    ///
    /// This is the primary key of the users table and is not updatable once set.
    /// The UUID is generated by Hibernate using the @UuidGenerator.
    @Id
    @GeneratedValue
    @UuidGenerator
    @Column(name = "user_id", updatable = false, nullable = false, columnDefinition = "UUID")
    private UUID userId;

    /// The user's email address. Required and must be unique across all users.
    ///
    /// Used for authentication and communication. Must be a valid email format.
    /// The email is case-insensitive and will be stored in lowercase.
    @Email(message = "Email should be valid")
    @NotBlank(message = "Email is required")
    @Column(nullable = false, unique = true, length = 255)
    private String email;

    /// The hashed password for the user. Required for email/password authentication.
    ///
    /// This should always store the hashed password, never plain text.
    /// The hashing should be done using a strong cryptographic hash function like BCrypt.
    @NotBlank(message = "Password hash is required")
    @Column(nullable = false)
    private String password;

    /// The user's full legal name. Required for all user accounts.
    ///
    /// This is the user's complete name as it should appear on official documents.
    /// Maximum of length is 255 characters.
    @NotBlank(message = "Full name is required")
    @Column(nullable = false, name = "full_name", length = 255)
    private String fullName;

    /// The user's unique username. Required and must be unique across all users.
    ///
    /// Used for @mentions and user identification. Must be between 3 and 50 characters.
    /// Only alphanumeric characters, dots, underscores, and hyphens are allowed.
    @NotBlank(message = "Username is required")
    @Column(unique = true, nullable = false, length = 50, name = "username")
    private String username;

    /// The user's phone number in valid format. Optional but must be unique if provided.
    @Column(length = 25, unique = true)
    private String phoneNumber;

    /// The user's role in the system. Defaults to PUBLIC.
    ///
    /// Determines the user's permissions and access levels within the application.
    /// Possible values are defined in the [Role] enum.
    ///
    /// @see Role
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Role role = Role.PUBLIC;


    /// The date and time when the user account was created.
    ///
    /// Automatically set by Hibernate when the entity is first persisted.
    /// Cannot be modified after creation.
    @CreationTimestamp
    @Column(name = "created_at", updatable = false, nullable = false)
    private LocalDateTime createdAt;

    /// The date and time when the user account was last updated.
    ///
    /// Automatically updated by Hibernate whenever the entity is modified.
    /// Cannot be set manually.
    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;


    // Empty constructor
    public User() {
    }

    // Constructor with all fields
    public User(String email, String password, String fullName, String username, String phoneNumber, Role role) {
        this.email = email;
        this.password = password;
        this.fullName = fullName;
        this.username = username;
        this.phoneNumber = phoneNumber;
        this.role = role;
    }

    public UUID getUserId() {
        return userId;
    }

    public void setUserId(UUID userId) {
        this.userId = userId;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    // Builder pattern
    public static class UserBuilder {
        private String email;
        private String password;
        private String fullName;
        private String username;
        private String phoneNumber;
        private Role role;

        public UserBuilder() {
        }

        public UserBuilder email(String email) {
            this.email = email;
            return this;
        }
        public UserBuilder password(String password) {
            this.password = password;
            return this;
        }
        public UserBuilder fullName(String fullName) {
            this.fullName = fullName;
            return this;
        }
        public UserBuilder username(String username) {
            this.username = username;
            return this;
        }
        public UserBuilder phoneNumber(String phoneNumber) {
            this.phoneNumber = phoneNumber;
            return this;
        }
        public UserBuilder role(Role role) {
            this.role = role;
            return this;
        }
        public User build() {
            return new User(email, password, fullName, username, phoneNumber, role);
        }

    }
}