/// Represents a user in the system with authentication and profile information.
///
/// This entity is the central identity model that supports multiple authentication methods,
/// including email/password and OAuth providers. It serves as the base for role-based access control
/// with support for PUBLIC, ADMIN, and LAWYER roles.
/// ### Key Features:
///
///     - Supports both traditional (email/password) and OAuth authentication
///     - Role-based access control with default to the PUBLIC role
///     - Email and phone verification status tracking
///     - Account activation/deactivation support
///     - Automatic audit fields (createdAt, updatedAt)
///     - Optional lawyer profile association for users with LAWYER role
///
/// ### Database Constraints:
///
///     - Unique constraint on (oauth_provider, oauth_id) for OAuth authentication
///     - Unique constraint on email, username, and phoneNumber
///     - Indexes on frequently queried fields for performance
///
///
/// @author shivaverabandi - BruteForce.com
/// @version 1.0
/// @since 2025-10-22
/// @see Role
/// @see LawyerProfile

package com.bruteforce.lawforall.model;
import jakarta.persistence.*;

import java.time.LocalDateTime;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.annotations.UuidGenerator;

import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

@Entity
@Table(
        name = "users",
        indexes = {
                @Index(name = "idx_user_username", columnList = "userName", unique = true),
                @Index(name = "idx_user_phone", columnList = "phoneNumber", unique = true),
                @Index(name = "idx_user_role_status", columnList = "role, isActive"),
                @Index(name = "idx_oauth", columnList = "oauthProvider, oauthId")
        },
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "uk_oauth_provider_id",
                        columnNames = {"oauthProvider", "oauthId"}
                )
        }
)
public class User {
    /// The user's unique identifier. Automatically generated as a UUID.
    ///
    /// This is the primary key of the users table and is not updatable once set.
    /// The UUID is generated by Hibernate using the @UuidGenerator.
    @Id
    @GeneratedValue
    @UuidGenerator
    @Column(name = "user_id", updatable = false, nullable = false, columnDefinition = "UUID")
    private UUID userId;

    /// The user's email address. Required and must be unique across all users.
    ///
    /// Used for authentication and communication. Must be a valid email format.
    /// The email is case-insensitive and will be stored in lowercase.
    @Email(message = "Email should be valid")
    @NotBlank(message = "Email is required")
    @Column(nullable = false, unique = true, length = 255)
    private String email;

    /// The hashed password for the user. Required for email/password authentication.
    ///
    /// This should always store the hashed password, never plain text.
    /// The hashing should be done using a strong cryptographic hash function like BCrypt.
    @NotBlank(message = "Password hash is required")
    @Column(nullable = false)
    private String password;

    /// The user's full legal name. Required for all user accounts.
    ///
    /// This is the user's complete name as it should appear on official documents.
    /// Maximum of length is 255 characters.
    @NotBlank(message = "Full name is required")
    @Column(nullable = false, name = "full_name", length = 255)
    private String fullName;

    /// The user's unique username. Required and must be unique across all users.
    ///
    /// Used for @mentions and user identification. Must be between 3 and 50 characters.
    /// Only alphanumeric characters, dots, underscores, and hyphens are allowed.
    @NotBlank(message = "Username is required")
    @Column(unique = true, nullable = false, length = 50, name = "user_name")
    private String userName;

    /// The user's phone number in valid format. Optional but must be unique if provided.
    @Column(length = 25, unique = true)
    private String phoneNumber;

    /// The user's role in the system. Defaults to PUBLIC.
    ///
    /// Determines the user's permissions and access levels within the application.
    /// Possible values are defined in the [Role] enum.
    ///
    /// @see Role
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Role role = Role.PUBLIC;

    /// The OAuth provider name if the user signed up via OAuth (e.g., "google", "facebook").
    ///
    /// This field is part of the composite unique constraint with oauthId.
    /// Null for users who signed up with email/password.
    @Column(name = "oauth_provider", length = 50)
    private String oauthProvider;

    /// The user's unique identifier from the OAuth provider.
    ///
    /// This is the external ID provided by the OAuth provider (e.g., Google's 'sub' claim).
    /// Part of the composite unique constraint with oauthProvider.
    @Column(name = "oauth_id", length = 100)
    private String oauthId;

    /// Indicates whether the user's email or phone number has been verified.
    ///
    /// Defaults to false. Should be set to true after the user verifies their email/phone.
    @Column(name = "is_verified", nullable = false)
    private Boolean isVerified = false;

    /// Indicates whether the user account is active.
    ///
    /// Set to false deactivate the account instead of deleting it.
    /// Deactivated users cannot log in but their data is preserved.
    @Column(name = "is_active", nullable = false)
    private Boolean isActive = true;

    /// The date and time when the user account was created.
    ///
    /// Automatically set by Hibernate when the entity is first persisted.
    /// Cannot be modified after creation.
    @CreationTimestamp
    @Column(name = "created_at", updatable = false, nullable = false)
    private LocalDateTime createdAt;

    /// The date and time when the user account was last updated.
    ///
    /// Automatically updated by Hibernate whenever the entity is modified.
    /// Cannot be set manually.
    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /// The lawyer profile associated with this user, if the user has the LAWYER role.
    ///
    /// This is a one-to-one relationship where the LawyerProfile is the owning side.
    /// The profile is automatically deleted if the user is deleted (orphanRemoval = true).
    /// Loaded lazily to improve performance.
    ///
    /// @see LawyerProfile
    ///
    @OneToOne(mappedBy = "user", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    private LawyerProfile lawyerProfile;

    /// The cases associated with this user as a public user.
    ///
    /// This is a one-to-many relationship where the LegalCase is the owning side.
    /// The cases are automatically deleted if the user is deleted (orphanRemoval = true).
    /// Loaded lazily to improve performance.
    ///
    /// @see LegalCase
    ///
    @OneToMany(mappedBy = "publicUser", cascade = CascadeType.ALL, orphanRemoval = true)
    private Set<LegalCase> publicUserCases = new HashSet<>();

    /// The cases associated with this user as a lawyer.
    ///
    /// This is a one-to-many relationship where the LegalCase is the owning side.
    /// The cases are automatically deleted if the user is deleted (orphanRemoval = true).
    /// Loaded lazily to improve performance.
    ///
    /// @see LegalCase
    ///
    @OneToMany(mappedBy = "lawyer", cascade = CascadeType.ALL)
    private Set<LegalCase> lawyerCases = new HashSet<>();


    // Empty constructor
    public User() {
    }

    // Constructor with email, password, and fullName
    public User(String email, String password, String fullName, String userName, String phoneNumber) {
        this.email = email;
        this.password = password;
        this.fullName = fullName;
        this.userName = userName;
        this.phoneNumber = phoneNumber;
    }

    // Constructor with all fields
    public User(UUID userId, String email, String password, String fullName, String userName,
                String phoneNumber, Role role, String oauthProvider, String oauthId,
                Boolean isVerified, Boolean isActive, LocalDateTime createdAt, LocalDateTime updatedAt,
                LawyerProfile lawyerProfile, Set<LegalCase> publicUserCases, Set<LegalCase> lawyerCases) {
        this.userId = userId;
        this.email = email;
        this.password = password;
        this.fullName = fullName;
        this.userName = userName;
        this.phoneNumber = phoneNumber;
        this.role = role;
        this.oauthProvider = oauthProvider;
        this.oauthId = oauthId;
        this.isVerified = isVerified;
        this.isActive = isActive;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.lawyerProfile = lawyerProfile;
        this.publicUserCases = publicUserCases;
        this.lawyerCases = lawyerCases;
    }


    // Getters and setters would go here

    public UUID getUserId() {
        return userId;
    }

    public void setUserId(UUID userId) {
        this.userId = userId;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    public String getOauthProvider() {
        return oauthProvider;
    }

    public void setOauthProvider(String oauthProvider) {
        this.oauthProvider = oauthProvider;
    }

    public String getOauthId() {
        return oauthId;
    }

    public void setOauthId(String oauthId) {
        this.oauthId = oauthId;
    }

    public Boolean getVerified() {
        return isVerified;
    }

    public void setVerified(Boolean verified) {
        isVerified = verified;
    }

    public Boolean getActive() {
        return isActive;
    }

    public void setActive(Boolean active) {
        isActive = active;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public LawyerProfile getLawyerProfile() {
        return lawyerProfile;
    }

    public void setLawyerProfile(LawyerProfile lawyerProfile) {
        this.lawyerProfile = lawyerProfile;
    }

    public Set<LegalCase> getPublicUserCases() {
        return publicUserCases;
    }

    public void setPublicUserCases(Set<LegalCase> publicUserCases) {
        this.publicUserCases = publicUserCases;
    }

    public Set<LegalCase> getLawyerCases() {
        return lawyerCases;
    }

    public void setLawyerCases(Set<LegalCase> lawyerCases) {
        this.lawyerCases = lawyerCases;
    }


    public static class Builder {
        private UUID userId;
        private String email;
        private String password;
        private String fullName;    // Changed from firstName
        private String userName;    // Added
        private String phoneNumber;
        private Role role = Role.PUBLIC;  // Added with default
        private String oauthProvider;
        private String oauthId;
        private Boolean isVerified = false;
        private Boolean isActive = true;
        private LocalDateTime createdAt;
        private LocalDateTime updatedAt;
        private LawyerProfile lawyerProfile;
        private Set<LegalCase> publicUserCases = new HashSet<>();
        private Set<LegalCase> lawyerCases = new HashSet<>();

        public Builder() {
        }

        public Builder userId(UUID userId) {
            this.userId = userId;
            return this;
        }

        public Builder email(String email) {
            this.email = email;
            return this;
        }

        public Builder password(String password) {
            this.password = password;
            return this;
        }

        public Builder oauthProvider(String oauthProvider) {
            this.oauthProvider = oauthProvider;
            return this;
        }

        public Builder oauthId(String oauthId) {
            this.oauthId = oauthId;
            return this;
        }

        public Builder firstName(String fullName) {
            this.fullName = fullName;
            return this;
        }
        public Builder lastName(String userName) {
            this.userName = userName;
            return this;
        }
        public Builder phoneNumber(String phoneNumber) {
            this.phoneNumber = phoneNumber;
            return this;
        }

        public Builder isVerified(Boolean isVerified) {
            this.isVerified = isVerified;
            return this;
        }

        public Builder isActive(Boolean isActive) {
            this.isActive = isActive;
            return this;
        }

        public Builder createdAt(LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        public Builder updatedAt(LocalDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }
        public Builder role(Role role) {
            this.role = role;
            return this;
        }

        public Builder lawyerProfile(LawyerProfile lawyerProfile) {
            this.lawyerProfile = lawyerProfile;
            return this;
        }

        public Builder publicUserCases(Set<LegalCase> publicUserCases) {
            this.publicUserCases = publicUserCases;
            return this;
        }

        public Builder lawyerCases(Set<LegalCase> lawyerCases) {
            this.lawyerCases = lawyerCases;
            return this;
        }

        public User build() {
            return new User(
                    userId, email, password, fullName,
                    userName, phoneNumber, role, oauthProvider, oauthId,
                    isVerified, isActive, createdAt, updatedAt, lawyerProfile,
                    publicUserCases, lawyerCases
            );
        }
    }
}